const { ctx, p, t } = await openRecorder(page, 1024, 768);
await p.goto(BASE + '/library');
await p.getByText('New Hire Onboarding', { exact: true }).first().waitFor({ timeout: 30000 });
await p.waitForTimeout(2500);
const marks = { start: t() };
await p.mouse.move(700, 300, { steps: 10 });
await p.waitForTimeout(600);
await glide(p, p.getByText('New Hire Onboarding', { exact: true }).first());
await p.getByText('Assignments').first().waitFor({ timeout: 30000 });
await p.waitForTimeout(3500);
await p.mouse.move(520, 450, { steps: 20 });
await smoothScroll(p, 520, 1600);
await p.waitForTimeout(2500);
await smoothScroll(p, -520, 1200);
await p.waitForTimeout(1200);
await glide(p, p.getByText('Reporting', { exact: true }).first());
await p.waitForTimeout(4500);
marks.end = t();
return await finish(ctx, p, 'detail', marks);
