const { ctx, p, t } = await openRecorder(page, 1024, 768);
await p.goto(BASE + '/users/1639256');
await p.getByRole('button', { name: 'Add profile image' }).waitFor({ timeout: 30000 });
await p.waitForTimeout(2500);
const marks = { start: t() };
await p.mouse.move(700, 500, { steps: 10 });
await p.waitForTimeout(500);
const chooser = p.waitForEvent('filechooser');
await glide(p, p.getByRole('button', { name: 'Add profile image' }));
await (await chooser).setFiles('/app/tmp/composer-uploads/1-prof_pick.jpg');
await p.getByRole('button', { name: 'Done' }).waitFor({ timeout: 30000 });
await p.waitForTimeout(2500);
await glide(p, p.getByRole('button', { name: 'Done' }));
await p.getByRole('button', { name: 'Remove' }).waitFor({ timeout: 30000 });
await p.waitForTimeout(1500);
await p.mouse.move(400, 290, { steps: 25 });
await p.waitForTimeout(1500);
await p.mouse.move(362, 88, { steps: 25 });
await p.waitForTimeout(3000);
marks.end = t();
return await finish(ctx, p, 'profile', marks);
