const { ctx, p, t } = await openRecorder(page, 1024, 768);
await p.goto(BASE + '/library/library-item/f654b186-79d6-4a1c-bb10-dcfe4dd4e27a');
await p.getByRole('button', { name: '4 thresholds' }).waitFor({ timeout: 30000 });
await p.waitForTimeout(2500);
const marks = { start: t() };
await p.mouse.move(500, 400, { steps: 10 });
await glide(p, p.getByRole('button', { name: '4 thresholds' }));
await p.getByText('Scoring thresholds').waitFor();
await p.waitForTimeout(4000);
await glide(p, p.getByRole('button', { name: 'Cancel' }));
await p.waitForTimeout(800);
await glide(p, p.getByRole('tab', { name: 'Reporting' }));
await p.getByText('Outcome').first().waitFor({ timeout: 30000 });
await p.waitForTimeout(1500);
await glide(p, p.getByText('Excellent').first(), { click: false, steps: 30 });
await p.waitForTimeout(1500);
await glide(p, p.getByText('Fair', { exact: true }).first(), { click: false, steps: 20 });
await p.waitForTimeout(3000);
marks.end = t();
return await finish(ctx, p, 'audit', marks);
